# PyTorch

In PyTorch, the computational graph is built up as you execute the code, as opposed to TensorFlow where you define your graph and then run it. 
In PyTorch, you create your graph by running it.

# Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [0]:
import torch
import numpy as np

Construct a matrix filled zeros and of dtype long:

![alt text](https://drive.google.com/uc?id=1mTiCspjN9hYj-PoiRpBiFLnb9izOVIqq)


In [38]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)
y = torch.zeros((5, 3), dtype = torch.long) # notice that both x and y have similar values
print(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


*Get* size of `x` using either `x.size()` or `x.shape`:

In [39]:
print(x.size())

torch.Size([5, 3])


**Note:** `torch.Size` is in fact a tuple, so it supports all tuple operations.

In [40]:
a, b = x.size()
print(a)
print(b)

5
3


In [41]:
print(x.shape)
print(x.size())
print(y.shape)
print(x == y)

torch.Size([5, 3])
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

Construct a 5x3 matrix, uninitialized:

In [42]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.0445e-36,  0.0000e+00,  2.3694e-38],
        [ 9.2196e-41,         nan,  0.0000e+00],
        [ 4.4721e+21,  1.5956e+25,  4.7399e+16],
        [ 3.7293e-08,  5.0063e-01,  1.6410e+00],
        [ 1.9465e+00,  5.9795e-01, -8.2768e-01]])


Construct a randomly initialized matrix:

In [43]:
x = torch.rand(5, 3)
print(x)
y = torch.rand((5, 3))
print(y)
print(x.shape)
print(x.size())
print(y.shape)

tensor([[5.2533e-01, 7.2033e-01, 4.9872e-02],
        [4.6395e-01, 6.2331e-01, 1.2973e-01],
        [2.9554e-01, 3.1602e-01, 3.1742e-01],
        [2.4346e-01, 1.4430e-04, 6.7515e-01],
        [2.4232e-01, 5.3492e-01, 3.6602e-01]])
tensor([[0.2947, 0.1207, 0.3778],
        [0.9009, 0.0046, 0.4386],
        [0.8854, 0.3801, 0.3994],
        [0.1423, 0.4627, 0.7389],
        [0.7095, 0.6481, 0.3535]])
torch.Size([5, 3])
torch.Size([5, 3])
torch.Size([5, 3])


Construct an Identity matrix

In [44]:
x = torch.eye(5, 5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


Construct a tensor directly from data:

`torch.tensor(data, dtype=None, device=None, requires_grad=False pin_memory=False)` → Tensor

Constructs a tensor with `data`.

![alt text](https://drive.google.com/uc?id=1YzeBactU2MQXI9q0dNJ3Q39cd6qD0oPb)


In [45]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.size())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


Or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [46]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

# rand_like will inherit all the attributes from its argument's tensor.
# This is true in general for any *_like() methods.
# Some of the other useful methods are torch.ones_like() and torch.zeros_like(). 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3416, -0.1944,  0.7297],
        [-1.1727,  0.9875,  0.8962],
        [-0.8377, -0.1544,  0.1387],
        [ 0.5596,  0.1958, -0.5802],
        [-1.0076,  1.4757, -0.5750]])


## Operations
There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [47]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.1825,  0.0896,  0.8594],
        [-0.4067,  1.2372,  1.2344],
        [-0.6092,  0.5259,  0.4282],
        [ 0.9298,  0.3851, -0.5204],
        [-0.1655,  2.4348, -0.4738]])


Addition: syntax 2

In [48]:
print(torch.add(x, y))

tensor([[ 0.1825,  0.0896,  0.8594],
        [-0.4067,  1.2372,  1.2344],
        [-0.6092,  0.5259,  0.4282],
        [ 0.9298,  0.3851, -0.5204],
        [-0.1655,  2.4348, -0.4738]])


Addition: providing an output tensor as argument

In [49]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.1825,  0.0896,  0.8594],
        [-0.4067,  1.2372,  1.2344],
        [-0.6092,  0.5259,  0.4282],
        [ 0.9298,  0.3851, -0.5204],
        [-0.1655,  2.4348, -0.4738]])


Addition: syntax 3

In [50]:
# adds 1 to y
print(y.add(1)) # also an example of "broadcasting" in PyTorch

tensor([[1.5241, 1.2840, 1.1297],
        [1.7660, 1.2496, 1.3382],
        [1.2285, 1.6802, 1.2895],
        [1.3701, 1.1894, 1.0597],
        [1.8421, 1.9591, 1.1012]])


Addition: in-place

In [51]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.1825,  0.0896,  0.8594],
        [-0.4067,  1.2372,  1.2344],
        [-0.6092,  0.5259,  0.4282],
        [ 0.9298,  0.3851, -0.5204],
        [-0.1655,  2.4348, -0.4738]])


**Note:** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example:` x.copy_(y), x.t_(),` will change `x`.

Matrix Multiplication, Transpose and Inverse is similar to NumPy with slight variations

In [52]:
m1 = torch.randn((5, 3))
m2 = torch.randn((5, 3))
print(m2.t() @ m1) # In NumPy this is equivalent to print(m2.T @ m1)
print(torch.inverse(m2.t() @ m1)) # In NumPy this is equivalent to print(inv(m2.T @ m1))
print((m2.t()).mm(m1)) # We can also use the mm() method to do matrix multiplications

tensor([[-1.9038, -5.0365,  4.4149],
        [-1.0219,  0.4375, -0.6824],
        [ 3.4664,  1.3597, -1.9030]])
tensor([[ 0.0110, -0.4118,  0.1731],
        [-0.4956, -1.3431, -0.6681],
        [-0.3342, -1.7098, -0.6876]])
tensor([[-1.9038, -5.0365,  4.4149],
        [-1.0219,  0.4375, -0.6824],
        [ 3.4664,  1.3597, -1.9030]])


You can use standard NumPy-like indexing with all bells and whistles!

In [53]:
print(x[:, 1])

tensor([-0.1944,  0.9875, -0.1544,  0.1958,  1.4757])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [54]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [55]:
x = torch.randn(1)
print(x)
print(x.item())
# temp = torch.rand(5, 3)
# print(temp)
# print(temp.item()) -> Throws this error : ValueError: only one element tensors can be converted to Python scalars

tensor([0.2825])
0.28252673149108887


### Broadcasting in PyTorch

Broadcasting in PyTorch is similar to broadcasting in NumPy

In [56]:
x = torch.ones((5, 3))
print(x)
print("*" * 65)

print(x + 1)
print(x.add(1))
print("*" * 65)

print(x * 3)
print("*" * 65)

print((x + 1) ** 2) 
print("*" * 65)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
*****************************************************************
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
*****************************************************************
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
*****************************************************************
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])
*****************************************************************


**Read Later:** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/torch).

### Some more useful methods of `torch`

### `torch.gather`

Gathers values along an axis specified by dim.

For a 3-D tensor the output is specified by:

```
out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2
```

*Parameters*

* **input** (`Tensor`) – the source tensor

* **dim** (`int`) – the axis along which to index

* **index** (`LongTensor`) – the indices of elements to gather

* **out** (`Tensor`, optional) – the destination tensor

* **sparse_grad** (`bool`, optional) – If `True`, gradient w.r.t. `input` will be a sparse tensor.

In [57]:
t = torch.tensor([[1,2],[3,4]])
print(torch.gather(t, 1, torch.tensor([[0,0],[1,0]])))

tensor([[1, 1],
        [4, 3]])


`torch.gather` creates a new tensor from the input tensor by taking the values from each row along the input dimension `dim`. The values in `torch.LongTensor`, passed as `index`, specify which value to take from each 'row'. The dimension of the output tensor is same as the dimension of index tensor. Following illustration from the official docs explains it more clearly:

![alt text](https://i.stack.imgur.com/nudGq.png)

(Note: In the illustration, indexing starts from 1 and not 0).

In first example, the dimension given is along rows (top to bottom), so for (1,1) position of `result`, it takes row value from the `index` for the `src` that is `1`. At (1,1) in source value is `1` so, outputs `1` at (1,1) in `result`. Similarly for (2,2) the row value from the index for `src` is `3`. At (3,2) the value in `src` is `8` and hence outputs `8` and so on.

Similarly for second example, indexing is along columns, and hence at (2,2) position of the `result`, the column value from the index for `src` is `3`, so at (2,3) from `src` ,`6` is taken and outputs to `result` at (2,2)

Source of this text cell : https://stackoverflow.com/a/54706716/6644968



In [58]:
# remember in PyTorch dim = 0 implies rows and dim = 1 implies columns
src = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
index = torch.LongTensor([[0, 1, 2], [1, 2, 0]])
result = torch.gather(input = src, dim = 0, index = index)
print(result)
# The position of elements of result w.r.t src matrix can be written as follows
# result = [[(0, 0), (1, 1), (2, 2)] [(1, 0), (2, 1), (0, 2)]]

tensor([[1, 5, 9],
        [4, 8, 3]])


### `torch.squeeze`

![alt text](https://drive.google.com/uc?id=1ohtcSu0VKZF8b68mXRGXvciEln8ycuXH)

In [59]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())

y = torch.squeeze(x)
print(y.size())

y = torch.squeeze(x, 0)
print(y.size())

y = torch.squeeze(x, 1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


### `torch.unsqueeze`

![alt text](https://drive.google.com/uc?id=1cQ7qLk3gtWZB6O70Un5VNJBH7L5_41Wp)

In [60]:
x = torch.tensor([1, 2, 3, 4])
print(x.size())
print("*" * 65)

print(torch.unsqueeze(x, 0))
print((torch.unsqueeze(x, 0)).size())
print("*" * 65)

print(torch.unsqueeze(x, 1))
print((torch.unsqueeze(x, 1)).size())
print("*" * 65)

torch.Size([4])
*****************************************************************
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
*****************************************************************
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])
*****************************************************************


### Putting it together (`gather` and `squeeze`)

In PyTorch you can perform the same operation using the `gather()` method. If `s` is a PyTorch Tensor of shape `(N, C)` and `y` is a PyTorch Tensor of shape `(N,)` containing longs in the range `0 <= y[i] < C`, then

`s.gather(1, y.view(-1, 1)).squeeze()`

will be a PyTorch Tensor of shape `(N,)` containing one entry from each row of `s`, selected according to the indices in `y`.

run the following cell to see an example.

In [61]:
# Example of using gather to select one entry from each row in PyTorch
def gather_example():
    N, C = 4, 5
    s = torch.randn(N, C)
    y = torch.LongTensor([1, 2, 1, 3])
    print(s)
    print(y)
    print(s.gather(1, y.view(-1, 1)).squeeze())
gather_example()

tensor([[-0.5164,  0.5133, -0.1107, -0.6624, -1.3124],
        [ 0.0332, -1.2098, -0.9295,  1.9885, -0.1014],
        [ 1.1397,  0.2071,  0.9834, -1.0199, -0.1085],
        [-0.6774,  0.1539,  0.4129,  0.2707, -1.7441]])
tensor([1, 2, 1, 3])
tensor([ 0.5133, -0.9295,  0.2071,  0.2707])


### `torch.max`

![alt text](https://drive.google.com/uc?id=1BWyunoD1xey8MRuADi9iSpBBrkS3TUL1)

In [62]:
a = torch.randn(1, 3)
print(a)

print(torch.max(a))

tensor([[ 1.2954, -0.4072, -0.1702]])
tensor(1.2954)


![alt text](https://drive.google.com/uc?id=184CwB5REsibX8RpXNfN_xVnXVhwG-rjj)

In [63]:
a = torch.randn(4, 4)
print(a)
print("*" * 65)

print(torch.max(a, dim = 1))
print("*" * 65)

values, indices = torch.max(a, 1)
print(values)
print(indices)
print("*" * 65)

tensor([[ 0.2808, -1.0512, -1.5355, -0.7470],
        [ 0.4536, -0.0678,  2.3143, -0.9477],
        [ 0.7300,  0.3678,  0.1796, -0.4506],
        [-1.4515, -1.5075, -0.8588,  0.6369]])
*****************************************************************
torch.return_types.max(
values=tensor([0.2808, 2.3143, 0.7300, 0.6369]),
indices=tensor([0, 2, 0, 3]))
*****************************************************************
tensor([0.2808, 2.3143, 0.7300, 0.6369])
tensor([0, 2, 0, 3])
*****************************************************************


![alt text](https://drive.google.com/uc?id=13aDh2cQ0pw8zROcV1rZIqdAMs4uwUmQ6)

In [64]:
a = torch.randn(4)
print(a)
b = torch.randn(4)
print(b)
print(torch.max(a, b))

tensor([ 0.8750, -1.2288, -1.6886,  0.1228])
tensor([-0.6866, -1.0096, -2.0394,  0.8701])
tensor([ 0.8750, -1.0096, -1.6886,  0.8701])


### `torch.abs()`

![alt text](https://drive.google.com/uc?id=1-XwicMO-HPvMDhYKxIHGxi8qgctUDNUl)

### `torch.cat`

![alt text](https://drive.google.com/uc?id=1gN9UzU_zBoG36dkV-r-iSyPil3AmPX09)

In [65]:
x = torch.randn(2, 3)
print(x)
print(x.size())
print("*" * 65)

print(torch.cat((x, x, x), 0))
print((torch.cat((x, x, x), 0)).size())
print("*" * 65)

print(torch.cat((x, x, x), 1))
print((torch.cat((x, x, x), 1)).size())
print("*" * 65)

tensor([[-0.2981, -0.3049,  0.5152],
        [ 0.6492, -1.3266, -0.1825]])
torch.Size([2, 3])
*****************************************************************
tensor([[-0.2981, -0.3049,  0.5152],
        [ 0.6492, -1.3266, -0.1825],
        [-0.2981, -0.3049,  0.5152],
        [ 0.6492, -1.3266, -0.1825],
        [-0.2981, -0.3049,  0.5152],
        [ 0.6492, -1.3266, -0.1825]])
torch.Size([6, 3])
*****************************************************************
tensor([[-0.2981, -0.3049,  0.5152, -0.2981, -0.3049,  0.5152, -0.2981, -0.3049,
          0.5152],
        [ 0.6492, -1.3266, -0.1825,  0.6492, -1.3266, -0.1825,  0.6492, -1.3266,
         -0.1825]])
torch.Size([2, 9])
*****************************************************************


## NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [66]:
a = torch.ones(5)
print(a)
print(a.size())

tensor([1., 1., 1., 1., 1.])
torch.Size([5])


In [67]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [68]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [69]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

One more way to use GPU (a more common approach) in Pytorch is as follows:

In [71]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cpu


You can move data to the GPU by doing `.to(device)` 

In [0]:
data = torch.eye(3)
data = data.to(device)

Bottomline is you can do pretty much everything just by using only Tensors!

# References

1.   [Deep Learning with PyTorch: A 60 minute blitz, Soumith Chintala](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

2.   [TORCH](https://pytorch.org/docs/stable/torch.html)

3. [Stefan Otte: Deep Neural Networks with PyTorch | PyData Berlin 2018](https://www.youtube.com/watch?v=_H3aw6wkCv0&t=821s)

4. [CS231n: Convolutional Neural Networks for Visual Recognition](http://cs231n.stanford.edu/)



